// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.zhang.netty.proto;

public final class Student {
  private Student() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhang_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhang_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhang_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhang_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhang_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhang_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhang_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhang_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhang_proto_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhang_proto_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhang_proto_StudentsAge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zhang_proto_StudentsAge_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\017com.zhang.proto\"\035\n\tMyRe" +
      "quest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResponse\022\020\n" +
      "\010realname\030\002 \001(\t\"\035\n\016StudentRequest\022\013\n\003age" +
      "\030\001 \001(\005\":\n\017StudentResponse\022\014\n\004name\030\001 \001(\t\022" +
      "\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"P\n\023StudentRes" +
      "ponseList\0229\n\017studentResponse\030\001 \003(\0132 .com" +
      ".zhang.proto.StudentResponse\"F\n\013Students" +
      "Age\0227\n\016studentRequest\030\001 \003(\0132\037.com.zhang." +
      "proto.StudentRequest2\362\002\n\016StudentService\022" +
      "H\n\013GetRealName\022\032.com.zhang.proto.MyReque" +
      "st\032\033.com.zhang.proto.MyResponse\"\000\022Y\n\020Get" +
      "StudentSByAge\022\037.com.zhang.proto.StudentR" +
      "equest\032 .com.zhang.proto.StudentResponse" +
      "\"\0000\001\022d\n\027GetStudentWrapperByAges\022\037.com.zh" +
      "ang.proto.StudentRequest\032$.com.zhang.pro" +
      "to.StudentResponseList\"\000(\001\022U\n\024GetStudent" +
      "sBySomeAge\022\032.com.zhang.proto.MyRequest\032\033" +
      ".com.zhang.proto.MyResponse\"\000(\0010\001B\"\n\025com" +
      ".zhang.netty.protoB\007StudentP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zhang_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zhang_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhang_proto_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_zhang_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zhang_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhang_proto_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_com_zhang_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_zhang_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhang_proto_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_com_zhang_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_zhang_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhang_proto_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_com_zhang_proto_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_zhang_proto_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhang_proto_StudentResponseList_descriptor,
        new String[] { "StudentResponse", });
    internal_static_com_zhang_proto_StudentsAge_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_zhang_proto_StudentsAge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zhang_proto_StudentsAge_descriptor,
        new String[] { "StudentRequest", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
