// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.zhang.netty.proto;

public interface StudentsAgeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zhang.proto.StudentsAge)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
   */
  java.util.List<StudentRequest>
      getStudentRequestList();
  /**
   * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
   */
  StudentRequest getStudentRequest(int index);
  /**
   * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
   */
  int getStudentRequestCount();
  /**
   * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
   */
  java.util.List<? extends StudentRequestOrBuilder>
      getStudentRequestOrBuilderList();
  /**
   * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
   */
  StudentRequestOrBuilder getStudentRequestOrBuilder(
          int index);
}
