// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.zhang.netty.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zhang.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *代表一个集合
   * </pre>
   *
   * <code>repeated .com.zhang.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<StudentResponse>
      getStudentResponseList();
  /**
   * <pre>
   *代表一个集合
   * </pre>
   *
   * <code>repeated .com.zhang.proto.StudentResponse studentResponse = 1;</code>
   */
  StudentResponse getStudentResponse(int index);
  /**
   * <pre>
   *代表一个集合
   * </pre>
   *
   * <code>repeated .com.zhang.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <pre>
   *代表一个集合
   * </pre>
   *
   * <code>repeated .com.zhang.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.zhang.netty.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <pre>
   *代表一个集合
   * </pre>
   *
   * <code>repeated .com.zhang.proto.StudentResponse studentResponse = 1;</code>
   */
  com.zhang.netty.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
          int index);
}
