// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.zhang.netty.proto;

/**
 * Protobuf type {@code com.zhang.proto.StudentsAge}
 */
public  final class StudentsAge extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.zhang.proto.StudentsAge)
    StudentsAgeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StudentsAge.newBuilder() to construct.
  private StudentsAge(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StudentsAge() {
    studentRequest_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StudentsAge(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              studentRequest_ = new java.util.ArrayList<StudentRequest>();
              mutable_bitField0_ |= 0x00000001;
            }
            studentRequest_.add(
                input.readMessage(StudentRequest.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        studentRequest_ = java.util.Collections.unmodifiableList(studentRequest_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Student.internal_static_com_zhang_proto_StudentsAge_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Student.internal_static_com_zhang_proto_StudentsAge_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            StudentsAge.class, Builder.class);
  }

  public static final int STUDENTREQUEST_FIELD_NUMBER = 1;
  private java.util.List<StudentRequest> studentRequest_;
  /**
   * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
   */
  public java.util.List<StudentRequest> getStudentRequestList() {
    return studentRequest_;
  }
  /**
   * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
   */
  public java.util.List<? extends StudentRequestOrBuilder>
      getStudentRequestOrBuilderList() {
    return studentRequest_;
  }
  /**
   * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
   */
  public int getStudentRequestCount() {
    return studentRequest_.size();
  }
  /**
   * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
   */
  public StudentRequest getStudentRequest(int index) {
    return studentRequest_.get(index);
  }
  /**
   * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
   */
  public StudentRequestOrBuilder getStudentRequestOrBuilder(
      int index) {
    return studentRequest_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < studentRequest_.size(); i++) {
      output.writeMessage(1, studentRequest_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < studentRequest_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, studentRequest_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof StudentsAge)) {
      return super.equals(obj);
    }
    StudentsAge other = (StudentsAge) obj;

    if (!getStudentRequestList()
        .equals(other.getStudentRequestList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStudentRequestCount() > 0) {
      hash = (37 * hash) + STUDENTREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getStudentRequestList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static StudentsAge parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StudentsAge parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StudentsAge parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StudentsAge parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StudentsAge parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StudentsAge parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StudentsAge parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StudentsAge parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static StudentsAge parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static StudentsAge parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static StudentsAge parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StudentsAge parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(StudentsAge prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.zhang.proto.StudentsAge}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.zhang.proto.StudentsAge)
      com.zhang.netty.proto.StudentsAgeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Student.internal_static_com_zhang_proto_StudentsAge_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Student.internal_static_com_zhang_proto_StudentsAge_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StudentsAge.class, Builder.class);
    }

    // Construct using com.zhang.netty.proto.StudentsAge.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStudentRequestFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (studentRequestBuilder_ == null) {
        studentRequest_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        studentRequestBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Student.internal_static_com_zhang_proto_StudentsAge_descriptor;
    }

    @Override
    public StudentsAge getDefaultInstanceForType() {
      return StudentsAge.getDefaultInstance();
    }

    @Override
    public StudentsAge build() {
      StudentsAge result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public StudentsAge buildPartial() {
      StudentsAge result = new StudentsAge(this);
      int from_bitField0_ = bitField0_;
      if (studentRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          studentRequest_ = java.util.Collections.unmodifiableList(studentRequest_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.studentRequest_ = studentRequest_;
      } else {
        result.studentRequest_ = studentRequestBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof StudentsAge) {
        return mergeFrom((StudentsAge)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(StudentsAge other) {
      if (other == StudentsAge.getDefaultInstance()) return this;
      if (studentRequestBuilder_ == null) {
        if (!other.studentRequest_.isEmpty()) {
          if (studentRequest_.isEmpty()) {
            studentRequest_ = other.studentRequest_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStudentRequestIsMutable();
            studentRequest_.addAll(other.studentRequest_);
          }
          onChanged();
        }
      } else {
        if (!other.studentRequest_.isEmpty()) {
          if (studentRequestBuilder_.isEmpty()) {
            studentRequestBuilder_.dispose();
            studentRequestBuilder_ = null;
            studentRequest_ = other.studentRequest_;
            bitField0_ = (bitField0_ & ~0x00000001);
            studentRequestBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStudentRequestFieldBuilder() : null;
          } else {
            studentRequestBuilder_.addAllMessages(other.studentRequest_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      StudentsAge parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (StudentsAge) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<StudentRequest> studentRequest_ =
      java.util.Collections.emptyList();
    private void ensureStudentRequestIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        studentRequest_ = new java.util.ArrayList<StudentRequest>(studentRequest_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        StudentRequest, StudentRequest.Builder, StudentRequestOrBuilder> studentRequestBuilder_;

    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public java.util.List<StudentRequest> getStudentRequestList() {
      if (studentRequestBuilder_ == null) {
        return java.util.Collections.unmodifiableList(studentRequest_);
      } else {
        return studentRequestBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public int getStudentRequestCount() {
      if (studentRequestBuilder_ == null) {
        return studentRequest_.size();
      } else {
        return studentRequestBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public StudentRequest getStudentRequest(int index) {
      if (studentRequestBuilder_ == null) {
        return studentRequest_.get(index);
      } else {
        return studentRequestBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public Builder setStudentRequest(
        int index, StudentRequest value) {
      if (studentRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentRequestIsMutable();
        studentRequest_.set(index, value);
        onChanged();
      } else {
        studentRequestBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public Builder setStudentRequest(
        int index, StudentRequest.Builder builderForValue) {
      if (studentRequestBuilder_ == null) {
        ensureStudentRequestIsMutable();
        studentRequest_.set(index, builderForValue.build());
        onChanged();
      } else {
        studentRequestBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public Builder addStudentRequest(StudentRequest value) {
      if (studentRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentRequestIsMutable();
        studentRequest_.add(value);
        onChanged();
      } else {
        studentRequestBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public Builder addStudentRequest(
        int index, StudentRequest value) {
      if (studentRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentRequestIsMutable();
        studentRequest_.add(index, value);
        onChanged();
      } else {
        studentRequestBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public Builder addStudentRequest(
        StudentRequest.Builder builderForValue) {
      if (studentRequestBuilder_ == null) {
        ensureStudentRequestIsMutable();
        studentRequest_.add(builderForValue.build());
        onChanged();
      } else {
        studentRequestBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public Builder addStudentRequest(
        int index, StudentRequest.Builder builderForValue) {
      if (studentRequestBuilder_ == null) {
        ensureStudentRequestIsMutable();
        studentRequest_.add(index, builderForValue.build());
        onChanged();
      } else {
        studentRequestBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public Builder addAllStudentRequest(
        Iterable<? extends StudentRequest> values) {
      if (studentRequestBuilder_ == null) {
        ensureStudentRequestIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, studentRequest_);
        onChanged();
      } else {
        studentRequestBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public Builder clearStudentRequest() {
      if (studentRequestBuilder_ == null) {
        studentRequest_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        studentRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public Builder removeStudentRequest(int index) {
      if (studentRequestBuilder_ == null) {
        ensureStudentRequestIsMutable();
        studentRequest_.remove(index);
        onChanged();
      } else {
        studentRequestBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public StudentRequest.Builder getStudentRequestBuilder(
        int index) {
      return getStudentRequestFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public StudentRequestOrBuilder getStudentRequestOrBuilder(
        int index) {
      if (studentRequestBuilder_ == null) {
        return studentRequest_.get(index);  } else {
        return studentRequestBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public java.util.List<? extends StudentRequestOrBuilder>
         getStudentRequestOrBuilderList() {
      if (studentRequestBuilder_ != null) {
        return studentRequestBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(studentRequest_);
      }
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public StudentRequest.Builder addStudentRequestBuilder() {
      return getStudentRequestFieldBuilder().addBuilder(
          StudentRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public StudentRequest.Builder addStudentRequestBuilder(
        int index) {
      return getStudentRequestFieldBuilder().addBuilder(
          index, StudentRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .com.zhang.proto.StudentRequest studentRequest = 1;</code>
     */
    public java.util.List<StudentRequest.Builder>
         getStudentRequestBuilderList() {
      return getStudentRequestFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        StudentRequest, StudentRequest.Builder, StudentRequestOrBuilder>
        getStudentRequestFieldBuilder() {
      if (studentRequestBuilder_ == null) {
        studentRequestBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            StudentRequest, StudentRequest.Builder, StudentRequestOrBuilder>(
                studentRequest_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        studentRequest_ = null;
      }
      return studentRequestBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.zhang.proto.StudentsAge)
  }

  // @@protoc_insertion_point(class_scope:com.zhang.proto.StudentsAge)
  private static final StudentsAge DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new StudentsAge();
  }

  public static StudentsAge getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StudentsAge>
      PARSER = new com.google.protobuf.AbstractParser<StudentsAge>() {
    @Override
    public StudentsAge parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StudentsAge(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StudentsAge> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<StudentsAge> getParserForType() {
    return PARSER;
  }

  @Override
  public StudentsAge getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

